In [1]:
import os
import numpy as np

import pandas as pd

import tensorflow as tf
import tensorflow_probability as tfp

import matplotlib.pyplot as plt

2024-07-18 15:35:59.168493: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-18 15:35:59.621124: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-18 15:35:59.621151: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-18 15:35:59.622916: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-18 15:35:59.850869: I tensorflow/core/platform/cpu_feature_g

# New York data: with structural zeros

In [2]:
df_ny = pd.read_csv("Data/NY/raw/ny_data.csv")

In [3]:
df = df_ny.copy()
df.head()

OWNERSHP  MORTGAGE AGE  SEX  MARST  RACESING  EDUC  EMPSTAT  DISABWRK  \
0         1         1  36    2      3         1    10        1         1   
1         1         1  18    2      6         1     5        3         1   
2         1         1  17    2      6         1     4        3         1   
3         1         3  51    1      1         1    10        1         1   
4         1         3  51    2      1         1     8        1         1   

   VETSTAT  
0        2  
1        1  
2        1  
3        2  
4        1

In [4]:
print("OWNERSHP")
print(np.unique(df[["OWNERSHP"]], return_counts=True)[0])
print(np.unique(df[["OWNERSHP"]], return_counts=True)[1])

counter = 0
for val in np.unique(df[["OWNERSHP"]], return_counts=True)[0]:

	condition = (df["OWNERSHP"]==val)
	df.loc[condition, "OWNERSHP"] = int(counter)

	counter = counter + 1

print("OWNERSHP")
print(np.unique(df[["OWNERSHP"]], return_counts=True)[0])
print(np.unique(df[["OWNERSHP"]], return_counts=True)[1])

OWNERSHP
[0 1 2]
[ 29039 571922 352115]
OWNERSHP
[0 1 2]
[ 29039 571922 352115]


In [5]:
print("MORTGAGE")
print(np.unique(df[["MORTGAGE"]], return_counts=True)[0])
print(np.unique(df[["MORTGAGE"]], return_counts=True)[1])

counter = 0
for val in np.unique(df[["MORTGAGE"]], return_counts=True)[0]:

	condition = (df["MORTGAGE"]==val)
	df.loc[condition, "MORTGAGE"] = int(counter)

	counter = counter + 1

print("MORTGAGE")
print(np.unique(df[["MORTGAGE"]], return_counts=True)[0])
print(np.unique(df[["MORTGAGE"]], return_counts=True)[1])

MORTGAGE
[0 1 3 4]
[381154 162251 406049   3622]
MORTGAGE
[0 1 2 3]
[381154 162251 406049   3622]


In [6]:
print("AGE")
print(np.unique(df[["AGE"]], return_counts=True)[0])
print(np.unique(df[["AGE"]], return_counts=True)[1])

counter = 1
bool_check = True
for val in np.unique(df[["AGE"]], return_counts=True)[0]:

	condition = (df["AGE"]==val)

	if counter == 8 and bool_check ==True:
		df.loc[condition, "AGE"] = int(0)
		bool_check = False

	else:
		df.loc[condition, "AGE"] = int(counter)
		counter = counter + 1

print("AGE")
print(np.unique(df[["AGE"]], return_counts=True)[0])
print(np.unique(df[["AGE"]], return_counts=True)[1])

AGE
['15' '16' '17' '18' '25' '36' '51' '<15' '>70']
[ 13292  13093  13455  82540 145106 219893 177662 201062  86973]
AGE
[0 1 2 3 4 5 6 7 8]
[201062  13292  13093  13455  82540 145106 219893 177662  86973]


In [7]:
print("SEX")
print(np.unique(df[["SEX"]], return_counts=True)[0])
print(np.unique(df[["SEX"]], return_counts=True)[1])

counter = 0
for val in np.unique(df[["SEX"]], return_counts=True)[0]:

	condition = (df["SEX"]==val)
	df.loc[condition, "SEX"] = int(counter)

	counter = counter + 1

print("SEX")
print(np.unique(df[["SEX"]], return_counts=True)[0])
print(np.unique(df[["SEX"]], return_counts=True)[1])

SEX
[1 2]
[459269 493807]
SEX
[0 1]
[459269 493807]


In [8]:
print("MARST")
print(np.unique(df[["MARST"]], return_counts=True)[0])
print(np.unique(df[["MARST"]], return_counts=True)[1])

counter = 0
for val in np.unique(df[["MARST"]], return_counts=True)[0]:

	condition = (df["MARST"]==val)
	df.loc[condition, "MARST"] = int(counter)

	counter = counter + 1

print("MARST")
print(np.unique(df[["MARST"]], return_counts=True)[0])
print(np.unique(df[["MARST"]], return_counts=True)[1])

MARST
[1 2 3 4 5 6]
[361144  27747  22999  59363  55134 426689]
MARST
[0 1 2 3 4 5]
[361144  27747  22999  59363  55134 426689]


In [9]:
print("RACESING")
print(np.unique(df[["RACESING"]], return_counts=True)[0])
print(np.unique(df[["RACESING"]], return_counts=True)[1])

counter = 0
for val in np.unique(df[["RACESING"]], return_counts=True)[0]:

	condition = (df["RACESING"]==val)
	df.loc[condition, "RACESING"] = int(counter)

	counter = counter + 1

print("RACESING")
print(np.unique(df[["RACESING"]], return_counts=True)[0])
print(np.unique(df[["RACESING"]], return_counts=True)[1])

RACESING
[1 2 3 4 5]
[763084 132899   5407  48414   3272]
RACESING
[0 1 2 3 4]
[763084 132899   5407  48414   3272]


In [10]:
print("EDUC")
print(np.unique(df[["EDUC"]], return_counts=True)[0])
print(np.unique(df[["EDUC"]], return_counts=True)[1])

counter = 0
for val in np.unique(df[["EDUC"]], return_counts=True)[0]:

	condition = (df["EDUC"]==val)
	df.loc[condition, "EDUC"] = int(counter)

	counter = counter + 1

print("EDUC")
print(np.unique(df[["EDUC"]], return_counts=True)[0])
print(np.unique(df[["EDUC"]], return_counts=True)[1])


EDUC
[ 0  1  2  3  4  5  6  7  8 10 11]
[ 80636  82611  92941  30820  34034  32280 284095  89785  51348 101673
  72853]
EDUC
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 80636  82611  92941  30820  34034  32280 284095  89785  51348 101673
  72853]


In [11]:
print("EMPSTAT")
print(np.unique(df[["EMPSTAT"]], return_counts=True)[0])
print(np.unique(df[["EMPSTAT"]], return_counts=True)[1])

counter = 0
for val in np.unique(df[["EMPSTAT"]], return_counts=True)[0]:

	condition = (df["EMPSTAT"]==val)
	df.loc[condition, "EMPSTAT"] = int(counter)

	counter = counter + 1

print("EMPSTAT")
print(np.unique(df[["EMPSTAT"]], return_counts=True)[0])
print(np.unique(df[["EMPSTAT"]], return_counts=True)[1])

EMPSTAT
[0 1 2 3]
[214354 419917  30440 288365]
EMPSTAT
[0 1 2 3]
[214354 419917  30440 288365]


In [12]:
print("DISABWRK")
print(np.unique(df[["DISABWRK"]], return_counts=True)[0])
print(np.unique(df[["DISABWRK"]], return_counts=True)[1])

counter = 0
for val in np.unique(df[["DISABWRK"]], return_counts=True)[0]:

	condition = (df["DISABWRK"]==val)
	df.loc[condition, "DISABWRK"] = int(counter)

	counter = counter + 1

print("DISABWRK")
print(np.unique(df[["DISABWRK"]], return_counts=True)[0])
print(np.unique(df[["DISABWRK"]], return_counts=True)[1])

DISABWRK
[0 1 4]
[214354 634052 104670]
DISABWRK
[0 1 2]
[214354 634052 104670]


In [13]:
print("VETSTAT")
print(np.unique(df[["VETSTAT"]], return_counts=True)[0])
print(np.unique(df[["VETSTAT"]], return_counts=True)[1])

counter = 0
for val in np.unique(df[["VETSTAT"]], return_counts=True)[0]:

	condition = (df["VETSTAT"]==val)
	df.loc[condition, "VETSTAT"] = int(counter)

	counter = counter + 1

print("VETSTAT")
print(np.unique(df[["VETSTAT"]], return_counts=True)[0])
print(np.unique(df[["VETSTAT"]], return_counts=True)[1])

VETSTAT
[0 1 2]
[227447 650967  74662]
VETSTAT
[0 1 2]
[227447 650967  74662]


In [14]:
df.head()

OWNERSHP  MORTGAGE AGE  SEX  MARST  RACESING  EDUC  EMPSTAT  DISABWRK  \
0         1         1   6    1      2         0     9        1         1   
1         1         1   4    1      5         0     5        3         1   
2         1         1   3    1      5         0     4        3         1   
3         1         2   7    0      0         0     9        1         1   
4         1         2   7    1      0         0     8        1         1   

   VETSTAT  
0        2  
1        1  
2        1  
3        2  
4        1

In [15]:
set_row = []
for row in df.columns:
    set_row.append(row)
    for col in df.columns:
        if row!=col:
            if (col in set_row)==False:
                print("###################################")
                print("###################################")
                print(pd.crosstab(df[row], df[col]))

###################################
###################################
MORTGAGE       0       1       2     3
OWNERSHP                              
0          29039       0       0     0
1              0  162251  406049  3622
2         352115       0       0     0
###################################
###################################
AGE            0     1     2     3      4      5       6       7      8
OWNERSHP                                                               
0            734   116   219   224   9584   3881    4438    2762   7081
1         117956  8604  8423  8622  34220  67427  142876  128297  55497
2          82372  4572  4451  4609  38736  73798   72579   46603  24395
###################################
###################################
SEX            0       1
OWNERSHP                
0          16233   12806
1         277865  294057
2         165171  186944
###################################
###################################
MARST          0      1      2  

## Build the domain vectors

In [16]:
n_j = np.zeros(len(df.columns))
for index in range(len(df.columns)):

    n_j[index] = df[df.columns[index]].max()
    
n_j = tf.convert_to_tensor(n_j+1, dtype = tf.float32)
max_categ = tf.expand_dims(tf.cast(tf.linspace(0, int(tf.reduce_max(n_j)) - 1, int(tf.reduce_max(n_j))), dtype = tf.float32), axis = 0)*tf.ones((tf.shape(n_j)[0], int(tf.reduce_max(n_j))))
ones_condition = max_categ<tf.expand_dims(n_j, axis = -1)*tf.ones((tf.shape(n_j)[0], int(tf.reduce_max(n_j))))

one_n_j = tf.where(ones_condition, tf.ones(tf.shape(ones_condition)), tf.zeros(tf.shape(ones_condition)))

2024-06-21 12:43:32.940411: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-21 12:43:33.155346: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-21 12:43:33.155390: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-21 12:43:33.158764: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-21 12:43:33.158805: I tensorflow/compile

In [17]:
# np.save("Data/NY/structural_zeros/SZ_NY_one_n_j.npy", one_n_j)

# X_ij_complete = np.array(df.values, dtype= int)

# # Shuffle the indices of the data
# indices = np.arange(X_ij_complete.shape[0])
# np.random.seed(1)
# np.random.shuffle(indices)

# X_ij_complete_shuffled = X_ij_complete[indices,:]
# np.save("Data/NY/structural_zeros/SZ_NY_indices.npy", indices)
# np.save("Data/NY/structural_zeros/SZ_NY_X_ij_full.npy", X_ij_complete_shuffled)

# n = 1000
# X_ij_included = X_ij_complete_shuffled[:n,:]
# np.save("Data/NY/structural_zeros/SZ_NY_X_ij_1000.npy", X_ij_included)

# n = 5000
# X_ij_included = X_ij_complete_shuffled[:n,:]
# np.save("Data/NY/structural_zeros/SZ_NY_X_ij_5000.npy", X_ij_included)

# n = 10000
# X_ij_included = X_ij_complete_shuffled[:n,:]
# np.save("Data/NY/structural_zeros/SZ_NY_X_ij_10000.npy", X_ij_included)

In [2]:
os.chdir("Scripts/")
%run -i mixed_membership_model.py
%run -i Manrique_Vallier.py
os.chdir("../")

In [3]:
one_n_j = tf.convert_to_tensor(np.load("Data/NY/structural_zeros/SZ_NY_one_n_j.npy"), dtype = tf.int32)
X_ij    = tf.convert_to_tensor(np.load("Data/NY/structural_zeros/SZ_NY_X_ij_full.npy"), dtype = tf.int32)

N = 953076

batch_size = 2048

n = 1000
X_ij_1000 = np.load("Data/NY/structural_zeros/SZ_NY_X_ij_1000.npy")
tau_in_data_1000 = step_tau_with_data(X_ij_1000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=1000 with $\tau$: ", tau_in_data_1000.numpy())

n = 5000
X_ij_5000 = np.load("Data/NY/structural_zeros/SZ_NY_X_ij_5000.npy")
tau_in_data_5000 = step_tau_with_data(X_ij_5000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=5000 with $\tau$: ", tau_in_data_5000.numpy())

n = 10000
X_ij_10000 = np.load("Data/NY/structural_zeros/SZ_NY_X_ij_10000.npy")
tau_in_data_10000 = step_tau_with_data(X_ij_10000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=10000 with $\tau$: ", tau_in_data_10000.numpy())


2024-06-21 13:52:44.922293: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-21 13:52:45.000800: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-21 13:52:45.000832: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-21 13:52:45.005529: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-21 13:52:45.005574: I tensorflow/compile

n=1000 with $\tau$:  11.0
n=5000 with $\tau$:  55.0
n=10000 with $\tau$:  88.0


## Build the disjoint constraints

In [4]:
os.chdir("Scripts/")
%run -i BNP_structural_zeros.py
%run -i manage_constraints.py
os.chdir("../")

In [5]:
current_constraint      = tf.convert_to_tensor([[1, 2, 0, 0, 0, 0,  0, 0, 0, 0],
						[1, 3, 0, 0, 0, 0,  0, 0, 0, 0],
						[1, 4, 0, 0, 0, 0,  0, 0, 0, 0],
						[2, 1, 0, 0, 0, 0,  0, 0, 0, 0],
						[3, 2, 0, 0, 0, 0,  0, 0, 0, 0],
						[3, 3, 0, 0, 0, 0,  0, 0, 0, 0],
						[3, 4, 0, 0, 0, 0,  0, 0, 0, 0],
						# [1, 0, 0, 0, 1, 0,  0, 0, 0, 0],
						[0, 0, 1, 0, 1, 0,  0, 0, 0, 0],
						[0, 0, 1, 0, 2, 0,  0, 0, 0, 0],
						[0, 0, 1, 0, 3, 0,  0, 0, 0, 0],
						[0, 0, 1, 0, 4, 0,  0, 0, 0, 0],
						[0, 0, 1, 0, 5, 0,  0, 0, 0, 0],
						[0, 0, 1, 0, 0, 0,  8, 0, 0, 0],
						[0, 0, 1, 0, 0, 0,  9, 0, 0, 0],
						[0, 0, 1, 0, 0, 0, 10, 0, 0, 0],
						[0, 0, 1, 0, 0, 0, 11, 0, 0, 0],
						[0, 0, 2, 0, 0, 0,  8, 0, 0, 0],
						[0, 0, 2, 0, 0, 0,  9, 0, 0, 0],
						[0, 0, 2, 0, 0, 0, 10, 0, 0, 0],
						[0, 0, 2, 0, 0, 0, 11, 0, 0, 0],
						[0, 0, 3, 0, 0, 0, 10, 0, 0, 0],
						[0, 0, 3, 0, 0, 0, 11, 0, 0, 0],
						[0, 0, 4, 0, 0, 0, 10, 0, 0, 0],
						[0, 0, 4, 0, 0, 0, 11, 0, 0, 0],
						[0, 0, 1, 0, 0, 0,  0, 2, 0, 0],
						[0, 0, 1, 0, 0, 0,  0, 3, 0, 0],
						[0, 0, 1, 0, 0, 0,  0, 4, 0, 0],
						[0, 0, 2, 0, 0, 0,  0, 2, 0, 0],
						[0, 0, 2, 0, 0, 0,  0, 3, 0, 0],
						[0, 0, 2, 0, 0, 0,  0, 4, 0, 0],
						[0, 0, 3, 0, 0, 0,  0, 1, 0, 0],
						[0, 0, 4, 0, 0, 0,  0, 1, 0, 0],
						[0, 0, 5, 0, 0, 0,  0, 1, 0, 0],
						[0, 0, 6, 0, 0, 0,  0, 1, 0, 0],
						[0, 0, 7, 0, 0, 0,  0, 1, 0, 0],
						[0, 0, 8, 0, 0, 0,  0, 1, 0, 0],
						[0, 0, 9, 0, 0, 0,  0, 1, 0, 0],
						[0, 0, 1, 0, 0, 0,  0, 0, 2, 0],
						[0, 0, 1, 0, 0, 0,  0, 0, 3, 0],
						[0, 0, 2, 0, 0, 0,  0, 0, 2, 0],
						[0, 0, 2, 0, 0, 0,  0, 0, 3, 0],
						[0, 0, 3, 0, 0, 0,  0, 0, 1, 0],
						[0, 0, 4, 0, 0, 0,  0, 0, 1, 0],
						[0, 0, 5, 0, 0, 0,  0, 0, 1, 0],
						[0, 0, 6, 0, 0, 0,  0, 0, 1, 0],
						[0, 0, 7, 0, 0, 0,  0, 0, 1, 0],
						[0, 0, 8, 0, 0, 0,  0, 0, 1, 0],
						[0, 0, 9, 0, 0, 0,  0, 0, 1, 0],
						[0, 0, 1, 0, 0, 0,  0, 0, 0, 2],
						[0, 0, 1, 0, 0, 0,  0, 0, 0, 3],
						[0, 0, 2, 0, 0, 0,  0, 0, 0, 2],
						[0, 0, 2, 0, 0, 0,  0, 0, 0, 3],
						[0, 0, 3, 0, 0, 0,  0, 0, 0, 2],
						[0, 0, 3, 0, 0, 0,  0, 0, 0, 3],
						[0, 0, 4, 0, 0, 0,  0, 0, 0, 1],
						[0, 0, 5, 0, 0, 0,  0, 0, 0, 1],
						[0, 0, 6, 0, 0, 0,  0, 0, 0, 1],
						[0, 0, 7, 0, 0, 0,  0, 0, 0, 1],
						[0, 0, 8, 0, 0, 0,  0, 0, 0, 1],
						[0, 0, 9, 0, 0, 0,  0, 0, 0, 1],
						# [0, 0, 0, 0, 0, 0,  8, 1, 0, 0],
						# [0, 0, 0, 0, 0, 0,  9, 1, 0, 0],
						# [0, 0, 0, 0, 0, 0, 10, 1, 0, 0],
						# [0, 0, 0, 0, 0, 0, 11, 1, 0, 0],
						# [0, 0, 0, 0, 0, 0,  8, 0, 1, 0],
						# [0, 0, 0, 0, 0, 0,  9, 0, 1, 0],
						# [0, 0, 0, 0, 0, 0, 10, 0, 1, 0],
						# [0, 0, 0, 0, 0, 0, 11, 0, 1, 0],
						# [0, 0, 0, 0, 0, 0, 10, 0, 0, 1],
						# [0, 0, 0, 0, 0, 0, 11, 0, 0, 1],
						# [0, 0, 0, 0, 0, 0,  0, 1, 2, 0],
						# [0, 0, 0, 0, 0, 0,  0, 1, 3, 0],
						# [0, 0, 0, 0, 0, 0,  0, 2, 1, 0],
						# [0, 0, 0, 0, 0, 0,  0, 3, 1, 0],
						# [0, 0, 0, 0, 0, 0,  0, 4, 1, 0],
						# [0, 0, 0, 0, 0, 0,  0, 0, 1, 2],
						# [0, 0, 0, 0, 0, 0,  0, 0, 1, 3]
						], dtype = tf.int32)
						

In [6]:
SZ_NY_one_n_j = tf.cast(np.load("Data/NY/structural_zeros/SZ_NY_one_n_j.npy"), dtype = tf.int32)

domain_j = tf.reduce_sum(SZ_NY_one_n_j, axis = 1)

In [7]:
# disjoint_constraint = iteration_disjoint_constraint(domain_j, current_constraint)
# np.save("Data/NY/structural_zeros/SZ_NY_disjoint_constraint_MV.npy", disjoint_constraint)

In [8]:
disjoint_constraint = np.load("Data/NY/structural_zeros/SZ_NY_disjoint_constraint_MV.npy")

## Synthetic data with structural zeros

In [9]:
os.chdir("Scripts/")
%run -i mixed_membership_model.py
%run -i Manrique_Vallier.py
os.chdir("../")

In [1]:
31265/1000000

0.031265

In [10]:
one_n_j = tf.convert_to_tensor(np.load("Data/NY/structural_zeros/SZ_NY_one_n_j.npy"), dtype = tf.float32)
a_0, b_0 = 2, 1

K = 15

N = 953076
N_test = 1000000

X_ij, theta_j_k, g_i, g_0 = param_mixed_membership_model(K, one_n_j, a_0, b_0, N_test)

check_constraints = current_constraint-1
observedX_ij = X_ij

for i in range(tf.shape(check_constraints)[0]):
	mask_check = (observedX_ij == check_constraints[i:i+1,...])
	mask_check = tf.where(check_constraints[i:i+1,...] ==-1, True, mask_check)

	observedX_ij = tf.gather(observedX_ij, tf.where(tf.reduce_all(mask_check, axis = 1)==False)[...,0], axis = 0)

while tf.shape(observedX_ij)[0]< N:
	print("Current size", tf.shape(observedX_ij)[0])

	newX_ij, g_i = param_mixed_membership_model_given(K, one_n_j, g_0, theta_j_k, N_test)

	for i in range(tf.shape(check_constraints)[0]):
		mask_check = (newX_ij == check_constraints[i:i+1,...])
		mask_check = tf.where(check_constraints[i:i+1,...] ==-1, True, mask_check)

		newX_ij = tf.gather(newX_ij, tf.where(tf.reduce_all(mask_check, axis = 1)==False)[...,0], axis = 0)

	observedX_ij = tf.concat((observedX_ij, newX_ij), axis = 0)

Current size tf.Tensor(31265, shape=(), dtype=int32)
Current size tf.Tensor(62009, shape=(), dtype=int32)
Current size tf.Tensor(93251, shape=(), dtype=int32)
Current size tf.Tensor(124621, shape=(), dtype=int32)
Current size tf.Tensor(155519, shape=(), dtype=int32)
Current size tf.Tensor(186604, shape=(), dtype=int32)
Current size tf.Tensor(217385, shape=(), dtype=int32)
Current size tf.Tensor(248666, shape=(), dtype=int32)
Current size tf.Tensor(279716, shape=(), dtype=int32)
Current size tf.Tensor(310954, shape=(), dtype=int32)
Current size tf.Tensor(341768, shape=(), dtype=int32)
Current size tf.Tensor(372625, shape=(), dtype=int32)
Current size tf.Tensor(403796, shape=(), dtype=int32)
Current size tf.Tensor(435021, shape=(), dtype=int32)
Current size tf.Tensor(466318, shape=(), dtype=int32)
Current size tf.Tensor(497329, shape=(), dtype=int32)
Current size tf.Tensor(528374, shape=(), dtype=int32)
Current size tf.Tensor(559336, shape=(), dtype=int32)
Current size tf.Tensor(590323, 

In [11]:
SZ_X_ij = observedX_ij[:N,...]
np.save("Data/NY/synthetic_structural_zeros/SZ_synthetic_NY_X_ij_full.npy", SZ_X_ij)
np.save("Data/NY/synthetic_structural_zeros/SZ_synthetic_NY_X_ij_1000.npy",  SZ_X_ij[:1000,...])
np.save("Data/NY/synthetic_structural_zeros/SZ_synthetic_NY_X_ij_5000.npy",  SZ_X_ij[:5000,...])
np.save("Data/NY/synthetic_structural_zeros/SZ_synthetic_NY_X_ij_10000.npy", SZ_X_ij[:10000,...])
np.save("Data/NY/synthetic_structural_zeros/SZ_NY_one_n_j.npy", one_n_j)

In [12]:
X_ij_1000

array([[2, 0, 7, ..., 1, 1, 1],
       [2, 0, 5, ..., 1, 1, 1],
       [1, 2, 6, ..., 1, 1, 1],
       ...,
       [1, 2, 0, ..., 0, 0, 0],
       [0, 0, 4, ..., 2, 1, 1],
       [1, 2, 0, ..., 0, 0, 0]])

In [13]:
one_n_j = tf.convert_to_tensor(np.load("Data/NY/synthetic_structural_zeros/SZ_NY_one_n_j.npy"), dtype = tf.int32)
X_ij    = tf.convert_to_tensor(np.load("Data/NY/synthetic_structural_zeros/SZ_synthetic_NY_X_ij_full.npy"), dtype = tf.int32)

N = 953076

batch_size = 2048

n = 1000
X_ij_1000 = np.load("Data/NY/synthetic_structural_zeros/SZ_synthetic_NY_X_ij_1000.npy")
tau_in_data_1000 = step_tau_with_data(X_ij_1000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=1000 with $\tau$: ", tau_in_data_1000.numpy())

n = 5000
X_ij_5000 = np.load("Data/NY/synthetic_structural_zeros/SZ_synthetic_NY_X_ij_5000.npy")
tau_in_data_5000 = step_tau_with_data(X_ij_5000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=5000 with $\tau$: ", tau_in_data_5000.numpy())

n = 10000
X_ij_10000 = np.load("Data/NY/synthetic_structural_zeros/SZ_synthetic_NY_X_ij_10000.npy")
tau_in_data_10000 = step_tau_with_data(X_ij_10000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=10000 with $\tau$: ", tau_in_data_10000.numpy())


n=1000 with $\tau$:  27.0
n=5000 with $\tau$:  91.0
n=10000 with $\tau$:  168.0


# New York data: without structural zeros

In [23]:
df_no_zeros = df[['AGE', 'SEX', 'MARST', 'RACESING', 'EDUC', 'EMPSTAT', 'DISABWRK', 'VETSTAT']].copy()

In [24]:
print("AGE")
print(np.unique(df_no_zeros[["AGE"]], return_counts=True)[0])
print(np.unique(df_no_zeros[["AGE"]], return_counts=True)[1])

df_no_zeros = df_no_zeros.loc[df_no_zeros["AGE"]>3].copy()

print("AGE")
print(np.unique(df_no_zeros[["AGE"]], return_counts=True)[0])
print(np.unique(df_no_zeros[["AGE"]], return_counts=True)[1])

AGE
[0 1 2 3 4 5 6 7 8]
[201062  13292  13093  13455  82540 145106 219893 177662  86973]
AGE
[4 5 6 7 8]
[ 82540 145106 219893 177662  86973]


In [25]:
for categorical in df_no_zeros.columns: 
	print(categorical)
	print(np.unique(df_no_zeros[[categorical]], return_counts=True)[0])
	print(np.unique(df_no_zeros[[categorical]], return_counts=True)[1])

	df_no_zeros[categorical]   = df_no_zeros[categorical] - df_no_zeros[categorical].min()
	
	print(categorical)
	print(np.unique(df_no_zeros[[categorical]], return_counts=True)[0])
	print(np.unique(df_no_zeros[[categorical]], return_counts=True)[1])

AGE
[4 5 6 7 8]
[ 82540 145106 219893 177662  86973]
AGE
[0 1 2 3 4]
[ 82540 145106 219893 177662  86973]
SEX
[0 1]
[335793 376381]
SEX
[0 1]
[335793 376381]
MARST
[0 1 2 3 4 5]
[361069  27218  22934  59345  55112 186496]
MARST
[0 1 2 3 4 5]
[361069  27218  22934  59345  55112 186496]
RACESING
[0 1 2 3 4]
[577672  91834   3657  36861   2150]
RACESING
[0 1 2 3 4]
[577672  91834   3657  36861   2150]
EDUC
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 11119   4789  35184  17448  21938  24682 281471  89679  51338 101673
  72853]
EDUC
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 11119   4789  35184  17448  21938  24682 281471  89679  51338 101673
  72853]
EMPSTAT
[1 2 3]
[413638  28626 269910]
EMPSTAT
[0 1 2]
[413638  28626 269910]
DISABWRK
[1 2]
[609000 103174]
DISABWRK
[0 1]
[609000 103174]
VETSTAT
[1 2]
[637522  74652]
VETSTAT
[0 1]
[637522  74652]


In [26]:
set_row = []
for row in df_no_zeros.columns:
    set_row.append(row)
    for col in df_no_zeros.columns:
        if row!=col:
            if (col in set_row)==False:
                print("###################################")
                print("###################################")
                print(pd.crosstab(df_no_zeros[row], df_no_zeros[col]))

###################################
###################################
SEX       0       1
AGE                
0     41736   40804
1     70628   74478
2    107208  112685
3     83139   94523
4     33082   53891
###################################
###################################
MARST       0     1     2      3      4      5
AGE                                           
0        6549  4314   791    413    225  70248
1       66700  6321  4950   7622    460  59053
2      138121  7255  9897  25340   2995  36285
3      113935  4851  6019  21645  16338  14874
4       35764  4477  1277   4325  35094   6036
###################################
###################################
RACESING       0      1     2      3    4
AGE                                      
0          62734  13436   564   5439  367
1         112269  21430   914   9953  540
2         177193  28669  1216  12078  737
3         148166  20861   736   7517  382
4          77310   7438   227   1874  124
#####################

In [27]:
os.chdir("Scripts/")
%run -i mixed_membership_model.py
%run -i Manrique_Vallier.py
os.chdir("../")

In [28]:
n_j = np.zeros(len(df_no_zeros.columns))
for index in range(len(df_no_zeros.columns)):

    n_j[index] = df_no_zeros[df_no_zeros.columns[index]].max()
    
n_j = tf.convert_to_tensor(n_j+1, dtype = tf.float32)
max_categ = tf.expand_dims(tf.cast(tf.linspace(0, int(tf.reduce_max(n_j)) - 1, int(tf.reduce_max(n_j))), dtype = tf.float32), axis = 0)*tf.ones((tf.shape(n_j)[0], int(tf.reduce_max(n_j))))
ones_condition = max_categ<tf.expand_dims(n_j, axis = -1)*tf.ones((tf.shape(n_j)[0], int(tf.reduce_max(n_j))))

one_n_j = tf.where(ones_condition, tf.ones(tf.shape(ones_condition)), tf.zeros(tf.shape(ones_condition)))

In [29]:
np.save("Data/NY/clean/NY_one_n_j.npy", one_n_j)

X_ij_complete = np.array(df_no_zeros.values, dtype= int)

# Shuffle the indices of the data
indices = np.arange(X_ij_complete.shape[0])
np.random.seed(1)
np.random.shuffle(indices)

X_ij_complete_shuffled = X_ij_complete[indices,:]
np.save("Data/NY/clean/NY_indices.npy", indices)
np.save("Data/NY/clean/NY_X_ij_full.npy", X_ij_complete_shuffled)

n = 1000
X_ij_included = X_ij_complete_shuffled[:n,:]
np.save("Data/NY/clean/NY_X_ij_1000.npy", X_ij_included)

n = 5000
X_ij_included = X_ij_complete_shuffled[:n,:]
np.save("Data/NY/clean/NY_X_ij_5000.npy", X_ij_included)

n = 10000
X_ij_included = X_ij_complete_shuffled[:n,:]
np.save("Data/NY/clean/NY_X_ij_10000.npy", X_ij_included)

In [30]:
one_n_j = tf.convert_to_tensor(np.load("Data/NY/clean/NY_one_n_j.npy"), dtype = tf.int32)
X_ij    = tf.convert_to_tensor(np.load("Data/NY/clean/NY_X_ij_full.npy"), dtype = tf.int32)

N = 712174

batch_size = 2048

n = 1000
X_ij_1000 = np.load("Data/NY/clean/NY_X_ij_1000.npy")
tau_in_data_1000 = step_tau_with_data(X_ij_1000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=1000 with $\tau$: ", tau_in_data_1000.numpy())

n = 5000
X_ij_5000 = np.load("Data/NY/clean/NY_X_ij_5000.npy")
tau_in_data_5000 = step_tau_with_data(X_ij_5000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=5000 with $\tau$: ", tau_in_data_5000.numpy())

n = 10000
X_ij_10000 = np.load("Data/NY/clean/NY_X_ij_10000.npy")
tau_in_data_10000 = step_tau_with_data(X_ij_10000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=10000 with $\tau$: ", tau_in_data_10000.numpy())

n=1000 with $\tau$:  9.0
n=5000 with $\tau$:  27.0
n=10000 with $\tau$:  53.0


In [31]:
X_ij.shape

TensorShape([712174, 8])

# Synthetic data

In [1]:
os.chdir("Scripts/")
%run -i mixed_membership_model.py
%run -i Manrique_Vallier.py
os.chdir("../")

NameError: name 'os' is not defined

In [30]:
one_n_j = tf.convert_to_tensor(np.load("Data/NY/clean/NY_one_n_j.npy"), dtype = tf.float32)
a_0, b_0 = 2, 1

K = 15

N = 712174

X_ij, theta_j_k, g_i, g_0 = param_mixed_membership_model(K, one_n_j, a_0, b_0, N)

In [31]:
X_ij, theta_j_k, g_i, g_0 = param_mixed_membership_model(K, one_n_j, a_0, b_0, N)

# np.save("Data/Synthetic/synth_X_ij_full.npy", X_ij)
# np.save("Data/Synthetic/synth_theta_j_k.npy", theta_j_k)
# np.save("Data/Synthetic/synth_g_i.npy", g_i)
# np.save("Data/Synthetic/synth_g_0.npy", g_0)
# np.save("Data/Synthetic/US_one_n_j.npy", one_n_j)

# n = 1000
# np.save("Data/Synthetic/synth_X_ij_1000.npy", X_ij[:n,:])

# n = 5000
# np.save("Data/Synthetic/synth_X_ij_5000.npy", X_ij[:n,:])

# n = 10000
# np.save("Data/Synthetic/synth_X_ij_10000.npy", X_ij[:n,:])

X_ij      = tf.convert_to_tensor(np.load("Data/Synthetic/synth_X_ij_full.npy"), dtype = tf.int32)
theta_j_k = tf.convert_to_tensor(np.load("Data/Synthetic/synth_theta_j_k.npy"), dtype = tf.float32)
g_i       = tf.convert_to_tensor(np.load("Data/Synthetic/synth_g_i.npy" ), dtype = tf.float32)
g_0       = tf.convert_to_tensor(np.load("Data/Synthetic/synth_g_0.npy" ), dtype = tf.float32)
one_n_j   = tf.convert_to_tensor(np.load("Data/Synthetic/US_one_n_j.npy"), dtype = tf.float32)

In [32]:
batch_size = 2048

X_ij_1000 = np.load("Data/Synthetic/synth_X_ij_1000.npy")
tau_in_data_1000 = step_tau_with_data(X_ij_1000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=1000 with $\tau$: ", tau_in_data_1000.numpy())

X_ij_5000 = np.load("Data/Synthetic/synth_X_ij_5000.npy")
tau_in_data_5000 = step_tau_with_data(X_ij_5000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=5000 with $\tau$: ", tau_in_data_5000.numpy())

X_ij_10000 = np.load("Data/Synthetic/synth_X_ij_10000.npy")
tau_in_data_10000 = step_tau_with_data(X_ij_10000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=10000 with $\tau$: ", tau_in_data_10000.numpy())

n=1000 with $\tau$:  4.0
n=5000 with $\tau$:  28.0
n=10000 with $\tau$:  66.0


# Synthetic data with structural zeros

In [1]:
import os
import numpy as np

import pandas as pd

import tensorflow as tf
import tensorflow_probability as tfp

import matplotlib.pyplot as plt

2024-07-18 17:02:23.600794: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-18 17:02:24.070202: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-18 17:02:24.070252: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-18 17:02:24.072153: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-18 17:02:24.414120: I tensorflow/core/platform/cpu_feature_g

In [2]:
os.chdir("Scripts/")
%run -i mixed_membership_model.py
%run -i Manrique_Vallier.py
os.chdir("../")

In [8]:
one_n_j = tf.convert_to_tensor(np.load("Data/NY/structural_zeros/SZ_NY_one_n_j.npy"), dtype = tf.float32)
a_0, b_0 = 2, 1

K = 15

N = 3*712174

X_ij, theta_j_k, g_i, g_0 = param_mixed_membership_model(K, one_n_j, a_0, b_0, N)

2024-07-18 17:03:44.542918: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-07-18 17:03:44.976466: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-07-18 17:03:44.976561: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-07-18 17:03:44.982377: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-07-18 17:03:44.982424: I tensorflow/compile

In [33]:
disjoint_constraint = tf.convert_to_tensor(np.load("Data/NY/structural_zeros/SZ_NY_disjoint_constraint_MV.npy"), dtype = tf.int32)-1

In [34]:
batch_size = 2**13
iterations = int(N/batch_size)

def body(input, i):

	condition_1 = tf.expand_dims(disjoint_constraint, axis = -1) == tf.expand_dims(tf.transpose(X_ij[i*batch_size:(i+1)*batch_size,...]), axis = 0)
	condition_2 = (tf.expand_dims(disjoint_constraint, axis = -1)*tf.ones(tf.shape(condition_1), dtype = tf.int32))==-1
	condition = tf.reduce_any(tf.stack((condition_1, condition_2)), axis = 0)

	return tf.reduce_any(tf.reduce_all(condition, axis = 1), axis = 0), tf.reduce_sum(tf.cast(tf.reduce_all(condition, axis = 1), tf.float32), axis = 1)

output = tf.scan(body, tf.range(0, iterations), initializer = (tf.zeros(batch_size, tf.int64)==0, tf.zeros(tf.shape(disjoint_constraint)[0])))
index_set = tf.reshape(output[0], [-1])
count_set = tf.reduce_sum(output[1], axis = 0)

In [35]:
condition_1 = tf.expand_dims(disjoint_constraint, axis = -1) == tf.expand_dims(tf.transpose(X_ij[iterations*batch_size:,...]), axis = 0)
condition_2 = (tf.expand_dims(disjoint_constraint, axis = -1)*tf.ones(tf.shape(condition_1), dtype = tf.int32))==-1
condition = tf.reduce_any(tf.stack((condition_1, condition_2)), axis = 0)

final_index_set = tf.reduce_any(tf.reduce_all(condition, axis = 1), axis = 0)

index = tf.where(tf.concat((index_set, final_index_set), axis = 0)==False)
count_set = count_set + tf.reduce_sum(tf.cast(tf.reduce_all(condition, axis = 1), tf.float32), axis = 1)

In [43]:
observed_Xij  = tf.gather(X_ij, index[:,0], axis = 0)
constraints_probabilities = count_set/N

In [47]:
np.save("Data/NY/synthetic_generated_structural_zeros/X_ij.npy", observed_Xij)
np.save("Data/NY/synthetic_generated_structural_zeros/X_ij_1000.npy", observed_Xij[:1000,...])
np.save("Data/NY/synthetic_generated_structural_zeros/constraints_probabilities.npy", constraints_probabilities)

In [3]:
X_ij = np.load("Data/NY/synthetic_generated_structural_zeros/X_ij.npy")
X_ij_1000 = np.load("Data/NY/synthetic_generated_structural_zeros/X_ij_1000.npy")

In [6]:
X_ij.shape[0]

76225

In [10]:
N = X_ij.shape[0]
batch_size = 2048

n = 1000
tau_in_data_1000 = step_tau_with_data(X_ij_1000, one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=1000 with $\tau$: ", tau_in_data_1000.numpy())

2024-07-18 17:04:13.885987: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xd95b8d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-07-18 17:04:13.886031: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 4070 Laptop GPU, Compute Capability 8.9
2024-07-18 17:04:13.986561: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-07-18 17:04:14.089815: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8907
2024-07-18 17:04:14.391312: I ./tensorflow/compiler/jit/device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


n=1000 with $\tau$:  91.0
