In [1]:
import os
import numpy as np

import tensorflow as tf
import tensorflow_probability as tfp

import matplotlib.pyplot as plt

2024-04-10 18:58:36.054904: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-10 18:58:36.143190: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-10 18:58:36.143245: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-10 18:58:36.143540: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-10 18:58:36.192517: I tensorflow/core/platform/cpu_feature_g

# Synthetic data

In [2]:
one_n_j = tf.convert_to_tensor(np.load("data/US/preprocessed/US_one_n_j.npy"), dtype = tf.float32)
a_0, b_0 = 20, 1

K = 15

N = 1150934

2024-04-10 18:58:38.667516: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-10 18:58:38.951463: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-10 18:58:38.951541: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-10 18:58:38.956835: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-10 18:58:38.956895: I tensorflow/compile

In [3]:
os.chdir("scripts/")
%run -i mixed_membership_model.py
%run -i Manrique_Vallier.py
os.chdir("../")

In [4]:
X_ij, theta_j_k, g_i, g_0 = param_mixed_membership_model(K, one_n_j, a_0, b_0, N)

2024-04-10 18:58:46.006674: I tensorflow/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory


In [6]:
# X_ij, theta_j_k, g_i, g_0 = param_mixed_membership_model(K, one_n_j, a_0, b_0, N)

# np.save("data/synthetic/synth_X_ij_full.npy", X_ij)
# np.save("data/synthetic/synth_theta_j_k.npy", theta_j_k)
# np.save("data/synthetic/synth_g_i.npy", g_i)
# np.save("data/synthetic/synth_g_0.npy", g_0)

X_ij      = tf.convert_to_tensor(np.load("data/synthetic/synth_X_ij_full.npy"), dtype = tf.int32)
theta_j_k = tf.convert_to_tensor(np.load("data/synthetic/synth_theta_j_k.npy"), dtype = tf.float32)
g_i       = tf.convert_to_tensor(np.load("data/synthetic/synth_g_i.npy"), dtype = tf.float32)
g_0       = tf.convert_to_tensor(np.load("data/synthetic/synth_g_0.npy"), dtype = tf.float32)

In [7]:
# np.save("data/synthetic/synth_X_ij_full.npy", X_ij)

batch_size = 2048

n = 1000
# np.save("data/synthetic/synth_X_ij_1000.npy", X_ij[:n,:])
tau_in_data_1000 = step_tau_with_data(X_ij[:n,:], one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=1000 with $\tau$: ", tau_in_data_1000.numpy())

n = 5000
# np.save("data/synthetic/synth_X_ij_5000.npy", X_ij[:n,:])
tau_in_data_5000 = step_tau_with_data(X_ij[:n,:], one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=5000 with $\tau$: ", tau_in_data_5000.numpy())

n = 10000
# np.save("data/synthetic/synth_X_ij_10000.npy", X_ij[:n,:])
tau_in_data_10000 = step_tau_with_data(X_ij[:n,:], one_n_j, X_ij[n:N,:], batch_size, N)
print(r"n=10000 with $\tau$: ", tau_in_data_10000.numpy())

n=1000 with $\tau$:  79.0
n=5000 with $\tau$:  391.0
n=10000 with $\tau$:  762.0


The above is not satisfying enough as it strictly depends on the choice of the other data... However it still gives huge estimates of tau so probably it does not affect it too much...

In [2]:
# a_0, b_0 = 1, 1
# a, b = 100, 1

# nr_simulation_DP = 200

# X_ij = nonparam_mixed_membership_model(one_n_j, a_0, b_0, a, b, int(N/batch_size), batch_size, nr_simulation_DP)

In [3]:
# batch_size = 2048

# n = 1000
# tau_in_data_1000 = step_tau_with_data(X_ij[:n,:], one_n_j, X_ij[n:N,:], batch_size, N)
# print(r"n=1000 with $\tau$: ", tau_in_data_1000.numpy())

# n = 5000
# tau_in_data_5000 = step_tau_with_data(X_ij[:n,:], one_n_j, X_ij[n:N,:], batch_size, N)
# print(r"n=1000 with $\tau$: ", tau_in_data_5000.numpy())

# n = 10000
# tau_in_data_10000 = step_tau_with_data(X_ij[:n,:], one_n_j, X_ij[n:N,:], batch_size, N)
# print(r"n=1000 with $\tau$: ", tau_in_data_10000.numpy())

# US data with structural

In [45]:
import pandas as pd
import numpy as np

In [46]:
df = pd.read_csv("data/US/raw/usa_00002.csv")
# df_2 = pd.read_csv("data/US/raw/usa_00003.csv")

df = df[["AGE", "SEX", "MARST", "RACE", "EDUC", "EMPSTAT", "INCTOT", "VETSTAT", "NCHILD", "HCOVANY"]]

In [49]:
df_1 = df.copy()

In [50]:
df_1 = df_1.drop(df_1[df_1["AGE"] == 999].index)
df_1.reset_index(drop=True, inplace=True)
df_1

AGE  SEX  MARST  RACE  EDUC  EMPSTAT   INCTOT  VETSTAT  NCHILD  \
0         19    2      6     1     6        3    -1500        1       0   
1         18    2      6     2     6        3     1600        1       0   
2         53    1      6     1     6        3    10000        1       0   
3         28    1      6     1     7        3        0        2       0   
4         25    2      6     1     3        3        0        1       0   
...      ...  ...    ...   ...   ...      ...      ...      ...     ...   
3214534    9    2      6     1     1        0  9999999        0       0   
3214535    7    2      6     1     1        0  9999999        0       0   
3214536   49    2      4     1     7        1    18500        1       1   
3214537   19    2      6     1     6        1    11500        1       0   
3214538   71    1      4     1     7        3    51700        2       0   

         HCOVANY  
0              2  
1              2  
2              1  
3              1  
4              2  
...          ...  
3214534        1  
3214535        1  
3214536        2  
3214537        1  
3214538        2  

[3214539 rows x 10 columns]

In [51]:
bins_age = [0, 15, 16, 17, 18, 24, 35, 50, 70, 120]
for i in range(9):

    condition = (df_1["AGE"]>bins_age[i]) & (df_1["AGE"]<=bins_age[i+1])
    df_1.loc[condition, "AGE"] = int(i)
    if i<3:
        cond_emp = df_1["EMPSTAT"]==0
        df_1.loc[condition & cond_emp, "EMPSTAT"] = int(3)

        cond_vet = df_1["VETSTAT"]==0
        df_1.loc[condition & cond_vet, "VETSTAT"] = int(1)

        cond_inc = df_1["INCTOT"]==9999999
        df_1.loc[condition & cond_inc, "INCTOT"] = int(0)

print(np.unique(df_1[["AGE"]], return_counts=True))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([571858,  39531,  40559,  46164, 230340, 428060, 575129, 891653,
       391245]))


In [52]:
condition = (df_1["NCHILD"]>=4)
df_1.loc[condition, "NCHILD"] = int(4)

np.unique(df_1[["NCHILD"]].values, return_counts=True)

(array([0, 1, 2, 3, 4]), array([2344205,  416004,  294007,  111908,   48415]))

In [53]:
df_1 = df_1.drop(df_1[df_1["SEX"] == 9].index)
df_1.reset_index(drop=True, inplace=True)

df_1 = df_1.drop(df_1[df_1["MARST"] == 9].index)
df_1.reset_index(drop=True, inplace=True)
df_1

AGE  SEX  MARST  RACE  EDUC  EMPSTAT  INCTOT  VETSTAT  NCHILD  \
0          4    2      6     1     6        3   -1500        1       0   
1          3    2      6     2     6        3    1600        1       0   
2          7    1      6     1     6        3   10000        1       0   
3          5    1      6     1     7        3       0        2       0   
4          5    2      6     1     3        3       0        1       0   
...      ...  ...    ...   ...   ...      ...     ...      ...     ...   
3214534    0    2      6     1     1        3       0        1       0   
3214535    0    2      6     1     1        3       0        1       0   
3214536    6    2      4     1     7        1   18500        1       1   
3214537    4    2      6     1     6        1   11500        1       0   
3214538    8    1      4     1     7        3   51700        2       0   

         HCOVANY  
0              2  
1              2  
2              1  
3              1  
4              2  
...          ...  
3214534        1  
3214535        1  
3214536        2  
3214537        1  
3214538        2  

[3214539 rows x 10 columns]

In [54]:
df_1["SEX"]   = df_1["SEX"] - df_1["SEX"].min()
print(np.unique(df_1[["SEX"]].values, return_counts=True))

df_1["MARST"] = df_1["MARST"] - df_1["MARST"].min()
print(np.unique(df_1[["MARST"]].values, return_counts=True))

(array([0, 1]), array([1574618, 1639921]))
(array([0, 1, 2, 3, 4, 5]), array([1315458,   60430,   44049,  289882,  171721, 1332999]))


In [55]:
race_sets = [{1}, {2}, {3,4,5,6}, {7}, {8,9}]
for i in range(5):

    condition = (df_1["RACE"]).isin(race_sets[i])
    df_1.loc[condition, "RACE"] = int(i)
    
print(np.unique(df_1[["RACE"]].values, return_counts=True))

(array([0, 1, 2, 3, 4]), array([2469925,  310237,  213739,  119050,  101588]))


In [56]:
df_1 = df_1.drop(df_1[df_1["EDUC"] == 99].index)
df_1.reset_index(drop=True, inplace=True)
df_1

AGE  SEX  MARST  RACE  EDUC  EMPSTAT  INCTOT  VETSTAT  NCHILD  \
0          4    1      5     0     6        3   -1500        1       0   
1          3    1      5     1     6        3    1600        1       0   
2          7    0      5     0     6        3   10000        1       0   
3          5    0      5     0     7        3       0        2       0   
4          5    1      5     0     3        3       0        1       0   
...      ...  ...    ...   ...   ...      ...     ...      ...     ...   
3214534    0    1      5     0     1        3       0        1       0   
3214535    0    1      5     0     1        3       0        1       0   
3214536    6    1      3     0     7        1   18500        1       1   
3214537    4    1      5     0     6        1   11500        1       0   
3214538    8    0      3     0     7        3   51700        2       0   

         HCOVANY  
0              2  
1              2  
2              1  
3              1  
4              2  
...          ...  
3214534        1  
3214535        1  
3214536        2  
3214537        1  
3214538        2  

[3214539 rows x 10 columns]

In [57]:
edu_sets = [{0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}, {8}, {9}, {10, 11}]
for i in range(11):

    condition = (df_1["EDUC"]).isin(edu_sets[i])
    df_1.loc[condition, "EDUC"] = int(i)

print(np.unique(df_1[["EDUC"]].values, return_counts=True))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10]), array([192718, 239568, 213469,  69213,  76684,  85612, 948049, 381192,
       213684, 794350]))


In [58]:
print(np.unique(df_1[["EMPSTAT"]].values, return_counts=True))
print(np.unique(df_1[["AGE"]], return_counts=True))

(array([0, 1, 2, 3]), array([  30440, 1509092,   71798, 1603209]))
(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([571858,  39531,  40559,  46164, 230340, 428060, 575129, 891653,
       391245]))


In [59]:
df_1 = df_1.drop(df_1[df_1["EMPSTAT"] == 9].index)
df_1 = df_1.drop(df_1[df_1["EMPSTAT"] == 0].index)
df_1.reset_index(drop=True, inplace=True)

In [60]:
df_1["EMPSTAT"] = df_1["EMPSTAT"] - df_1["EMPSTAT"].min()
print(np.unique(df_1[["EMPSTAT"]].values, return_counts=True))

(array([0, 1, 2]), array([1509092,   71798, 1603209]))


In [61]:
df_1 = df_1.drop(df_1[df_1["INCTOT"] == 9999999].index)
df_1 = df_1.drop(df_1[df_1["INCTOT"] == 9999998].index)
df_1.reset_index(drop=True, inplace=True)
df_1

AGE  SEX  MARST  RACE  EDUC  EMPSTAT  INCTOT  VETSTAT  NCHILD  \
0          4    1      5     0     6        2   -1500        1       0   
1          3    1      5     1     6        2    1600        1       0   
2          7    0      5     0     6        2   10000        1       0   
3          5    0      5     0     7        2       0        2       0   
4          5    1      5     0     3        2       0        1       0   
...      ...  ...    ...   ...   ...      ...     ...      ...     ...   
3184094    0    1      5     0     1        2       0        1       0   
3184095    0    1      5     0     1        2       0        1       0   
3184096    6    1      3     0     7        0   18500        1       1   
3184097    4    1      5     0     6        0   11500        1       0   
3184098    8    0      3     0     7        2   51700        2       0   

         HCOVANY  
0              2  
1              2  
2              1  
3              1  
4              2  
...          ...  
3184094        1  
3184095        1  
3184096        2  
3184097        1  
3184098        2  

[3184099 rows x 10 columns]

In [62]:
condition = df_1["INCTOT"]<0
df_1.loc[condition, "INCTOT"] = -1
condition = df_1["INCTOT"]>300000
df_1.loc[condition, "INCTOT"] = 300005
bins_inc = [-1000, 2000, 11000, 20000, 31000, 45000, 60000, 80000, 120000, 200000, df_1["INCTOT"].max()+1]
# plt.hist( df_1["INCTOT"].values, bins = bins_inc)
for i in range(10):

    condition = (df_1["INCTOT"]>bins_inc[i]) & (df_1["INCTOT"]<=bins_inc[i+1])
    df_1.loc[condition, "INCTOT"] = int(i)

print(np.unique(df_1[["INCTOT"]].values, return_counts=True))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([943362, 368759, 369447, 346250, 340832, 263869, 205818, 185130,
       100884,  59748]))


In [63]:
df_1 = df_1.drop(df_1[df_1["VETSTAT"] == 0].index)
df_1 = df_1.drop(df_1[df_1["VETSTAT"] == 9].index)
df_1.reset_index(drop=True, inplace=True)
df_1

AGE  SEX  MARST  RACE  EDUC  EMPSTAT  INCTOT  VETSTAT  NCHILD  \
0          4    1      5     0     6        2       0        1       0   
1          3    1      5     1     6        2       0        1       0   
2          7    0      5     0     6        2       1        1       0   
3          5    0      5     0     7        2       0        2       0   
4          5    1      5     0     3        2       0        1       0   
...      ...  ...    ...   ...   ...      ...     ...      ...     ...   
3184094    0    1      5     0     1        2       0        1       0   
3184095    0    1      5     0     1        2       0        1       0   
3184096    6    1      3     0     7        0       2        1       1   
3184097    4    1      5     0     6        0       2        1       0   
3184098    8    0      3     0     7        2       5        2       0   

         HCOVANY  
0              2  
1              2  
2              1  
3              1  
4              2  
...          ...  
3184094        1  
3184095        1  
3184096        2  
3184097        1  
3184098        2  

[3184099 rows x 10 columns]

In [64]:
df_1["HCOVANY"] = df_1["HCOVANY"] - df_1["HCOVANY"].min()
print(np.unique(df_1[["HCOVANY"]].values, return_counts=True))

df_1["VETSTAT"] = df_1["VETSTAT"] - df_1["VETSTAT"].min()
print(np.unique(df_1[["VETSTAT"]].values, return_counts=True))

(array([0, 1]), array([ 250168, 2933931]))
(array([0, 1]), array([2980460,  203639]))


In [87]:
set_row = []
for row in df_1.columns:
    set_row.append(row)
    for col in df_1.columns:
        if row!=col:
            if (col in set_row)==False:
                print("###################################")
                print("###################################")
                print(pd.crosstab(df_1[row], df_1[col]))


###################################
###################################
SEX       0       1
AGE                
0    277366  264052
1     20526   19005
2     21064   19495
3     23402   22762
4    118147  112193
5    215618  212442
6    284698  290431
7    428117  463536
8    169989  221256
###################################
###################################
MARST       0      1      2       3       4       5
AGE                                                
0          47    230     45       0       6  541090
1          65    227     38      15      11   39175
2          81    256     47      27       7   40141
3         242    351     14      29      19   45509
4       15770   3857    754    1026     131  208802
5      177423  11755   6910   19821     868  211283
6      359922  14263  15035   72319    5242  108348
7      564954  18767  17806  150674   50353   89099
8      196954  10724   3400   45971  115084   19112
###################################
############################

In [91]:
import tensorflow as tf

In [93]:
n_j = np.zeros(len(df_1.columns))
for index in range(len(df_1.columns)):

    n_j[index] = df_1[df_1.columns[index]].max()
    
n_j = tf.convert_to_tensor(n_j+1, dtype = tf.float32)
max_categ = tf.expand_dims(tf.cast(tf.linspace(0, int(tf.reduce_max(n_j)) - 1, int(tf.reduce_max(n_j))), dtype = tf.float32), axis = 0)*tf.ones((tf.shape(n_j)[0], int(tf.reduce_max(n_j))))
ones_condition = max_categ<tf.expand_dims(n_j, axis = -1)*tf.ones((tf.shape(n_j)[0], int(tf.reduce_max(n_j))))

one_n_j = tf.where(ones_condition, tf.ones(tf.shape(ones_condition)), tf.zeros(tf.shape(ones_condition)))

In [95]:
# X_ij_complete = df_1.values
# np.save("data/US/structural_zeros/US_one_n_j.npy", one_n_j)
# np.save("data/US/structural_zeros/US_X_ij_full.npy", X_ij_complete)

# # Shuffle the indices of the data
# indices = np.arange(X_ij_complete.shape[0])
# np.random.seed(42)
# np.random.shuffle(indices)
# np.save("data/US/structural_zeros/US_indices.npy", indices)

In [97]:
# X_ij_complete_shuffled = X_ij_complete[indices,:]

# n = 1000
# X_ij_included = X_ij_complete_shuffled[:n,:]
# np.save("data/US/structural_zeros/US_X_ij_1000.npy", X_ij_included)

# n = 5000
# X_ij_included = X_ij_complete_shuffled[:n,:]
# np.save("data/US/structural_zeros/US_X_ij_5000.npy", X_ij_included)

# n = 10000
# X_ij_included = X_ij_complete_shuffled[:n,:]
# np.save("data/US/structural_zeros/US_X_ij_10000.npy", X_ij_included)

# US data

In [ ]:
# choice 3 keep nr child as it is
# choice 4 collapse nr child to >4
# choice 5 collapse nr child to >3, marst to married, separated, single, race 7,8,9 together, educ 0,1,2 together
# preprocessed is the final version

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/US/raw/usa_00002.csv")
# df_2 = pd.read_csv("data/US/raw/usa_00003.csv")

df = df[["AGE", "SEX", "MARST", "RACE", "EDUC", "EMPSTAT", "INCTOT", "VETSTAT", "NCHILD", "HCOVANY"]]

In [11]:
df_1 = df.loc[df["AGE"]>=21].copy()
print(np.unique(df_1[["AGE"]].values))

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68
 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92
 93 94 95 96]


In [12]:
df_1 = df_1.drop(df_1[df_1["AGE"] == 999].index)
df_1.reset_index(drop=True, inplace=True)
df_1

AGE  SEX  MARST  RACE  EDUC  EMPSTAT  INCTOT  VETSTAT  NCHILD  \
0         53    1      6     1     6        3   10000        1       0   
1         28    1      6     1     7        3       0        2       0   
2         25    2      6     1     3        3       0        1       0   
3         30    2      6     1     6        3       0        1       0   
4         66    2      5     1     7        3   15000        1       0   
...      ...  ...    ...   ...   ...      ...     ...      ...     ...   
2432318   77    1      1     1     6        3   32100        2       0   
2432319   41    1      4     1     6        1   42100        1       3   
2432320   34    2      6     1    10        1   47500        1       3   
2432321   49    2      4     1     7        1   18500        1       1   
2432322   71    1      4     1     7        3   51700        2       0   

         HCOVANY  
0              1  
1              1  
2              2  
3              2  
4              2  
...          ...  
2432318        2  
2432319        2  
2432320        2  
2432321        2  
2432322        2  

[2432323 rows x 10 columns]

In [13]:
bins_age = [0, 30, 38, 46, 54, 60, 66, 72, 80, 90, 100]
for i in range(10):

    condition = (df_1["AGE"]>bins_age[i]) & (df_1["AGE"]<=bins_age[i+1])
    df_1.loc[condition, "AGE"] = int(i)

print(np.unique(df_1[["AGE"]], return_counts=True))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([379083, 311243, 294992, 335651, 285958, 274653, 229521, 188128,
       107239,  25855]))


In [14]:
condition = (df_1["NCHILD"]>=4)
df_1.loc[condition, "NCHILD"] = int(4)

np.unique(df_1[["NCHILD"]].values, return_counts=True)

(array([0, 1, 2, 3, 4]), array([1564997,  413546,  293564,  111833,   48383]))

In [15]:
df_1 = df_1.drop(df_1[df_1["SEX"] == 9].index)
df_1.reset_index(drop=True, inplace=True)

df_1 = df_1.drop(df_1[df_1["MARST"] == 9].index)
df_1.reset_index(drop=True, inplace=True)
df_1

AGE  SEX  MARST  RACE  EDUC  EMPSTAT  INCTOT  VETSTAT  NCHILD  \
0          3    1      6     1     6        3   10000        1       0   
1          0    1      6     1     7        3       0        2       0   
2          0    2      6     1     3        3       0        1       0   
3          0    2      6     1     6        3       0        1       0   
4          5    2      5     1     7        3   15000        1       0   
...      ...  ...    ...   ...   ...      ...     ...      ...     ...   
2432318    7    1      1     1     6        3   32100        2       0   
2432319    2    1      4     1     6        1   42100        1       3   
2432320    1    2      6     1    10        1   47500        1       3   
2432321    3    2      4     1     7        1   18500        1       1   
2432322    6    1      4     1     7        3   51700        2       0   

         HCOVANY  
0              1  
1              1  
2              2  
3              2  
4              2  
...          ...  
2432318        2  
2432319        2  
2432320        2  
2432321        2  
2432322        2  

[2432323 rows x 10 columns]

In [16]:
df_1["SEX"]   = df_1["SEX"] - df_1["SEX"].min()
print(np.unique(df_1[["SEX"]].values, return_counts=True))

df_1["MARST"] = df_1["MARST"] - df_1["MARST"].min()
print(np.unique(df_1[["MARST"]].values, return_counts=True))

(array([0, 1]), array([1173604, 1258719]))
(array([0, 1, 2, 3, 4, 5]), array([1313565,   58491,   43822,  289715,  171643,  555087]))


In [17]:
race_sets = [{1}, {2}, {3,4,5,6}, {7}, {8,9}]
for i in range(5):

    condition = (df_1["RACE"]).isin(race_sets[i])
    df_1.loc[condition, "RACE"] = int(i)
    
print(np.unique(df_1[["RACE"]].values, return_counts=True))

(array([0, 1, 2, 3, 4]), array([1910525,  229186,  160338,   80737,   51537]))


In [18]:
df_1 = df_1.drop(df_1[df_1["EDUC"] == 99].index)
df_1.reset_index(drop=True, inplace=True)
df_1

AGE  SEX  MARST  RACE  EDUC  EMPSTAT  INCTOT  VETSTAT  NCHILD  \
0          3    0      5     0     6        3   10000        1       0   
1          0    0      5     0     7        3       0        2       0   
2          0    1      5     0     3        3       0        1       0   
3          0    1      5     0     6        3       0        1       0   
4          5    1      4     0     7        3   15000        1       0   
...      ...  ...    ...   ...   ...      ...     ...      ...     ...   
2432318    7    0      0     0     6        3   32100        2       0   
2432319    2    0      3     0     6        1   42100        1       3   
2432320    1    1      5     0    10        1   47500        1       3   
2432321    3    1      3     0     7        1   18500        1       1   
2432322    6    0      3     0     7        3   51700        2       0   

         HCOVANY  
0              1  
1              1  
2              2  
3              2  
4              2  
...          ...  
2432318        2  
2432319        2  
2432320        2  
2432321        2  
2432322        2  

[2432323 rows x 10 columns]

In [19]:
edu_sets = [{0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}, {8}, {9}, {10, 11}]
for i in range(11):

    condition = (df_1["EDUC"]).isin(edu_sets[i])
    df_1.loc[condition, "EDUC"] = int(i)

print(np.unique(df_1[["EDUC"]].values, return_counts=True))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10]), array([ 36913,  11870,  55975,  29366,  37140,  42267, 870888, 343087,
       210941, 793876]))


In [20]:
print(np.unique(df_1[["EMPSTAT"]].values, return_counts=True))
print(np.unique(df_1[["AGE"]], return_counts=True))

(array([1, 2, 3]), array([1431899,   59093,  941331]))
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([379083, 311243, 294992, 335651, 285958, 274653, 229521, 188128,
       107239,  25855]))


In [21]:
df_1 = df_1.drop(df_1[df_1["EMPSTAT"] == 9].index)
df_1 = df_1.drop(df_1[df_1["EMPSTAT"] == 0].index)
df_1.reset_index(drop=True, inplace=True)

In [22]:
df_1["EMPSTAT"] = df_1["EMPSTAT"] - df_1["EMPSTAT"].min()
print(np.unique(df_1[["EMPSTAT"]].values, return_counts=True))

(array([0, 1, 2]), array([1431899,   59093,  941331]))


In [23]:
df_1 = df_1.drop(df_1[df_1["INCTOT"] == 9999999].index)
df_1 = df_1.drop(df_1[df_1["INCTOT"] == 9999998].index)
df_1.reset_index(drop=True, inplace=True)
df_1

AGE  SEX  MARST  RACE  EDUC  EMPSTAT  INCTOT  VETSTAT  NCHILD  \
0          3    0      5     0     6        2   10000        1       0   
1          0    0      5     0     7        2       0        2       0   
2          0    1      5     0     3        2       0        1       0   
3          0    1      5     0     6        2       0        1       0   
4          5    1      4     0     7        2   15000        1       0   
...      ...  ...    ...   ...   ...      ...     ...      ...     ...   
2432318    7    0      0     0     6        2   32100        2       0   
2432319    2    0      3     0     6        0   42100        1       3   
2432320    1    1      5     0    10        0   47500        1       3   
2432321    3    1      3     0     7        0   18500        1       1   
2432322    6    0      3     0     7        2   51700        2       0   

         HCOVANY  
0              1  
1              1  
2              2  
3              2  
4              2  
...          ...  
2432318        2  
2432319        2  
2432320        2  
2432321        2  
2432322        2  

[2432323 rows x 10 columns]

In [24]:
condition = df_1["INCTOT"]<0
df_1.loc[condition, "INCTOT"] = -1
condition = df_1["INCTOT"]>300000
df_1.loc[condition, "INCTOT"] = 300005
bins_inc = [-1000, 2000, 11000, 20000, 31000, 45000, 60000, 80000, 120000, 200000, df_1["INCTOT"].max()+1]
# plt.hist( df_1["INCTOT"].values, bins = bins_inc)
for i in range(10):

    condition = (df_1["INCTOT"]>bins_inc[i]) & (df_1["INCTOT"]<=bins_inc[i+1])
    df_1.loc[condition, "INCTOT"] = int(i)

print(np.unique(df_1[["INCTOT"]].values, return_counts=True))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([278774, 307502, 353393, 339636, 338690, 263277, 205512, 185017,
       100845,  59677]))


In [25]:
df_1 = df_1.drop(df_1[df_1["VETSTAT"] == 0].index)
df_1 = df_1.drop(df_1[df_1["VETSTAT"] == 9].index)
df_1.reset_index(drop=True, inplace=True)
df_1

AGE  SEX  MARST  RACE  EDUC  EMPSTAT  INCTOT  VETSTAT  NCHILD  \
0          3    0      5     0     6        2       1        1       0   
1          0    0      5     0     7        2       0        2       0   
2          0    1      5     0     3        2       0        1       0   
3          0    1      5     0     6        2       0        1       0   
4          5    1      4     0     7        2       2        1       0   
...      ...  ...    ...   ...   ...      ...     ...      ...     ...   
2432318    7    0      0     0     6        2       4        2       0   
2432319    2    0      3     0     6        0       4        1       3   
2432320    1    1      5     0    10        0       5        1       3   
2432321    3    1      3     0     7        0       2        1       1   
2432322    6    0      3     0     7        2       5        2       0   

         HCOVANY  
0              1  
1              1  
2              2  
3              2  
4              2  
...          ...  
2432318        2  
2432319        2  
2432320        2  
2432321        2  
2432322        2  

[2432323 rows x 10 columns]

In [26]:
df_1["HCOVANY"] = df_1["HCOVANY"] - df_1["HCOVANY"].min()
print(np.unique(df_1[["HCOVANY"]].values, return_counts=True))

df_1["VETSTAT"] = df_1["VETSTAT"] - df_1["VETSTAT"].min()
print(np.unique(df_1[["VETSTAT"]].values, return_counts=True))

(array([0, 1]), array([ 206843, 2225480]))
(array([0, 1]), array([2229109,  203214]))


In [27]:
set_row = []
for row in df_1.columns:
    set_row.append(row)
    for col in df_1.columns:
        if row!=col:
            if (col in set_row)==False:
                print("###################################")
                print("###################################")
                print(pd.crosstab(df_1[row], df_1[col]))


###################################
###################################
SEX       0       1
AGE                
0    193030  186053
1    155631  155612
2    146126  148866
3    164492  171159
4    137937  148021
5    130705  143948
6    108413  121108
7     85957  102171
8     43686   63553
9      7627   18228
###################################
###################################
MARST       0     1     2      3      4       5
AGE                                            
0       88545  9307  3666   8007    421  269137
1      172367  8543  6713  23256   1016   99348
2      185964  7284  7986  36461   2330   54967
3      213173  7791  8714  54244   6099   45630
4      180143  6207  6440  49978  10978   32212
5      175094  5561  4745  46650  18510   24093
6      145175  4422  2941  35522  27037   14424
7      107766  4426  1740  24257  40860    9079
8       41572  3938   748   9685  46402    4894
9        3766  1012   129   1655  17990    1303
###################################
####

In [30]:
import tensorflow as tf

In [31]:
n_j = np.zeros(len(df_1.columns))
for index in range(len(df_1.columns)):

    n_j[index] = df_1[df_1.columns[index]].max()
    
n_j = tf.convert_to_tensor(n_j+1, dtype = tf.float32)
max_categ = tf.expand_dims(tf.cast(tf.linspace(0, int(tf.reduce_max(n_j)) - 1, int(tf.reduce_max(n_j))), dtype = tf.float32), axis = 0)*tf.ones((tf.shape(n_j)[0], int(tf.reduce_max(n_j))))
ones_condition = max_categ<tf.expand_dims(n_j, axis = -1)*tf.ones((tf.shape(n_j)[0], int(tf.reduce_max(n_j))))

one_n_j = tf.where(ones_condition, tf.ones(tf.shape(ones_condition)), tf.zeros(tf.shape(ones_condition)))

In [32]:
# X_ij_complete = df_1.values
# np.save("data/US/preprocessed/US_one_n_j.npy", one_n_j)
# np.save("data/US/preprocessed/US_X_ij_full.npy", X_ij_complete)

# # Shuffle the indices of the data
# indices = np.arange(X_ij_complete.shape[0])
# np.random.seed(42)
# np.random.shuffle(indices)
# np.save("data/US/preprocessed/US_indices.npy", indices)

In [33]:
# X_ij_complete_shuffled = X_ij_complete[indices,:]

# n = 1000
# X_ij_included = X_ij_complete_shuffled[:n,:]
# np.save("data/US/preprocessed/US_X_ij_1000.npy", X_ij_included)

# n = 5000
# X_ij_included = X_ij_complete_shuffled[:n,:]
# np.save("data/US/preprocessed/US_X_ij_5000.npy", X_ij_included)

# n = 10000
# X_ij_included = X_ij_complete_shuffled[:n,:]
# np.save("data/US/preprocessed/US_X_ij_10000.npy", X_ij_included)

# US data

In [79]:
# choice 3 keep nr child as it is
# choice 4 collapse nr child to >4
# choice 5 collapse nr child to >3, marst to married, separated, single, race 7,8,9 together, educ 0,1,2 together
# preprocessed is the final version

In [80]:
import pandas as pd

In [85]:
df = pd.read_csv("data/US/raw/usa_00002.csv")
# df_2 = pd.read_csv("data/US/raw/usa_00003.csv")

df = df[["NCHILD", "AGE", "SEX", "MARST", "RACE", "EDUC", "EMPSTAT", "INCTOT", "HCOVANY", "VETSTAT"]]

In [86]:
df_1 = df.loc[df["AGE"]>=21].copy()
print(np.unique(df_1[["AGE"]].values))

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68
 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92
 93 94 95 96]


In [87]:
condition = (df_1["NCHILD"]>=4)
df_1.loc[condition, "NCHILD"] = int(4)

np.unique(df_1[["NCHILD"]].values, return_counts=True)

(array([0, 1, 2, 3, 4]), array([1564997,  413546,  293564,  111833,   48383]))

In [88]:
bins_age = [0, 30, 38, 46, 54, 60, 66, 72, 80, 90, 100]
for i in range(10):

    condition = (df_1["AGE"]>bins_age[i]) & (df_1["AGE"]<=bins_age[i+1])
    df_1.loc[condition, "AGE"] = int(i)

print(np.unique(df_1[["AGE"]], return_counts=True))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([379083, 311243, 294992, 335651, 285958, 274653, 229521, 188128,
       107239,  25855]))


In [89]:
df_1["SEX"]   = df_1["SEX"] - df_1["SEX"].min()
print(np.unique(df_1[["SEX"]].values, return_counts=True))

df_1["MARST"] = df_1["MARST"] - df_1["MARST"].min()
print(np.unique(df_1[["MARST"]].values, return_counts=True))

(array([0, 1]), array([1173604, 1258719]))
(array([0, 1, 2, 3, 4, 5]), array([1313565,   58491,   43822,  289715,  171643,  555087]))


In [90]:
race_sets = [{1}, {2}, {3,4,5,6}, {7}, {8,9}]
for i in range(5):

    condition = (df_1["RACE"]).isin(race_sets[i])
    df_1.loc[condition, "RACE"] = int(i)
    
print(np.unique(df_1[["RACE"]].values, return_counts=True))

(array([0, 1, 2, 3, 4]), array([1910525,  229186,  160338,   80737,   51537]))


In [91]:
edu_sets = [{0, 1}, {2}, {3, 4, 5, 6}, {7, 8, 9, 10}, {11}]
for i in range(5):

    condition = (df_1["EDUC"]).isin(edu_sets[i])
    df_1.loc[condition, "EDUC"] = int(i)

print(np.unique(df_1[["EDUC"]].values, return_counts=True))

(array([0, 1, 2, 3, 4]), array([  48783,   55975,  979661, 1040121,  307783]))


In [92]:
df_1["EMPSTAT"] = df_1["EMPSTAT"] - df_1["EMPSTAT"].min()
print(np.unique(df_1[["EMPSTAT"]].values, return_counts=True))

(array([0, 1, 2]), array([1431899,   59093,  941331]))


In [93]:
condition = df_1["INCTOT"]<0
df_1.loc[condition, "INCTOT"] = -1
condition = df_1["INCTOT"]>300000
df_1.loc[condition, "INCTOT"] = 300005
bins_inc = [-1000, 2000, 11000, 20000, 31000, 45000, 60000, 80000, 120000, 200000, df_1["INCTOT"].max()+1]
# plt.hist( df_1["INCTOT"].values, bins = bins_inc)
for i in range(10):

    condition = (df_1["INCTOT"]>bins_inc[i]) & (df_1["INCTOT"]<=bins_inc[i+1])
    df_1.loc[condition, "INCTOT"] = int(i)

print(np.unique(df_1[["INCTOT"]].values, return_counts=True))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([278774, 307502, 353393, 339636, 338690, 263277, 205512, 185017,
       100845,  59677]))


In [94]:
df_1["HCOVANY"] = df_1["HCOVANY"] - df_1["HCOVANY"].min()
print(np.unique(df_1[["HCOVANY"]].values, return_counts=True))

df_1["VETSTAT"] = df_1["VETSTAT"] - df_1["VETSTAT"].min()
print(np.unique(df_1[["VETSTAT"]].values, return_counts=True))

(array([0, 1]), array([ 206843, 2225480]))
(array([0, 1]), array([2229109,  203214]))


In [95]:
n_j = np.zeros(len(df_1.columns))
for index in range(len(df_1.columns)):

    n_j[index] = df_1[df_1.columns[index]].max()
    
n_j = tf.convert_to_tensor(n_j+1, dtype = tf.float32)
max_categ = tf.expand_dims(tf.cast(tf.linspace(0, int(tf.reduce_max(n_j)) - 1, int(tf.reduce_max(n_j))), dtype = tf.float32), axis = 0)*tf.ones((tf.shape(n_j)[0], int(tf.reduce_max(n_j))))
ones_condition = max_categ<tf.expand_dims(n_j, axis = -1)*tf.ones((tf.shape(n_j)[0], int(tf.reduce_max(n_j))))

one_n_j = tf.where(ones_condition, tf.ones(tf.shape(ones_condition)), tf.zeros(tf.shape(ones_condition)))


In [98]:
# X_ij_complete = df_1.values
# np.save("data/US/preprocessed/US_one_n_j.npy", one_n_j)
# np.save("data/US/preprocessed/US_X_ij_full.npy", X_ij_complete)

# # Shuffle the indices of the data
# indices = np.arange(X_ij_complete.shape[0])
# np.random.seed(42)
# np.random.shuffle(indices)
# np.save("data/US/preprocessed/US_indices.npy", indices)

In [99]:
# X_ij_complete_shuffled = X_ij_complete[indices,:]

# n = 1000
# X_ij_included = X_ij_complete_shuffled[:n,:]
# np.save("data/US/preprocessed/US_X_ij_1000.npy", X_ij_included)

# n = 5000
# X_ij_included = X_ij_complete_shuffled[:n,:]
# np.save("data/US/preprocessed/US_X_ij_5000.npy", X_ij_included)

# n = 10000
# X_ij_included = X_ij_complete_shuffled[:n,:]
# np.save("data/US/preprocessed/US_X_ij_10000.npy", X_ij_included)

In [164]:
one_n_j = np.load("data/US/choice_4/US_one_n_j.npy")

indeces   = np.load("data/US/choice_4/US_indices.npy")
X_ij_full = np.load("data/US/choice_4/US_X_ij_full.npy")[indeces,:]

X_ij_1000  = np.load("data/US/choice_4/US_X_ij_1000.npy")
X_ij_5000  = np.load("data/US/choice_4/US_X_ij_5000.npy")
X_ij_10000 = np.load("data/US/choice_4/US_X_ij_10000.npy")

In [165]:
for i in range(10):
    unique_values, freq = np.unique(X_ij_full[:,i], return_counts=True)
    print(freq)

[1564997  413546  293564  111833   48383]
[379083 311243 294992 335651 285958 274653 229521 188128 107239  25855]
[1173604 1258719]
[1313565   58491   43822  289715  171643  555087]
[1910525  229186  160338   80737   51537]
[  48783   55975  979661 1040121  307783]
[1431899   59093  941331]
[278774 307502 353393 339636 338690 263277 205512 185017 100845  59677]
[ 206843 2225480]
[2229109  203214]


In [166]:
os.chdir("scripts/")
%run -i mixed_membership_model.py
%run -i Manrique_Vallier.py
os.chdir("../")

In [167]:
N = 1150934
J = tf.shape(one_n_j)[0]
batch_size = 2048

n = 1000
tau_in_data_1000 = step_tau_with_data(X_ij_1000, one_n_j, X_ij_full[n:N,:], batch_size, N)
print(r"n=1000 with $\tau$: ", tau_in_data_1000.numpy())

n = 5000
tau_in_data_5000 = step_tau_with_data(X_ij_5000, one_n_j, X_ij_full[n:N,:], batch_size, N)
print(r"n=5000 with $\tau$: ", tau_in_data_5000.numpy())

n = 10000
tau_in_data_10000 = step_tau_with_data(X_ij_10000, one_n_j, X_ij_full[n:N,:], batch_size, N)
print(r"n=10000 with $\tau$: ", tau_in_data_10000.numpy())

n=1000 with $\tau$:  41.0
n=5000 with $\tau$:  182.0
n=10000 with $\tau$:  372.0


In [168]:
34.24/2 + 450 + 90/2 + (100+47)/2

585.62